### ISSUE TITLE
[Feature] Auto-Sync for Links

### ISSUE THREAD

**Issue by tobeanywhere** [windingwind/zotero-better-notes#1124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: 13.6.9
- Zotero Version: 7.0.3
- Plugin Version: latest

### Describe the feature request

It is very cumbersome and challenging to keep "import linked note" up to date manually

### Describe the solution you'd like

Ideally, "import link notes" should update automatically when the content of the linked note changes. Or at least have a button for a quick update instead of having to deactivate and activate the import every time.

**Comment by windingwind** [comment]
To clarify, you shouldn't expect the `embedded` linked notes to be updated, as they are just copies of the original notes. That's why we use links—they are just placeholders for the original notes, and you can point to them from anywhere in any note.

If you want to preview the linked note, use the hover-to-preview feature;
If you want to edit the linked note, ctrl-click the link to open it in the context pane;
If you do want the linked note to be embedded, use the export with links embedded option or the embed link feature

But if all above do not satisfy your needs, I would suggest that the note-link mechanism isn't designed for you.
