### ISSUE TITLE
Automatically synchronize all notes from the entire Zotero library to Obsidian.

### ISSUE THREAD

**Issue by MuYe142857** [windingwind/zotero-better-notes#1198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

- OS: Windows 11 23H2
- Zotero Version: 7.0.9 
- Plugin Version: 2.1.4

### Describe the feature request

**Is your feature request related to a problem? Please describe.**
Nothing to do with the problem, just trying to add a feature.

**Why do you need this feature?**
I have a lot of md notes in my zotero library and I want to export them all to Obsidian for management but I can't find a quick and efficient way to do it.Can you add a feature that automatically detects all notes in Zotero's library and exports them all.

### Describe the solution you'd like

**The solution you'd like**
Detect all notes in the Zotero library, including entry notes and standalone notes. If the note has already been exported to the Obsidian folder, update it; if it has never been exported, export it to the Obsidian folder. All notes are updated bidirectionally between Obsidian and Zotero. Of course, I hope this is a feature that can be turned on and off.

**Alternatives you've considered**

**Comment by ct2034** [comment]
I second this request. It would improve the collaboration between obsidian and zotero.
Especially for those already having a large library, it is simply unfeasible to go through every note and manually set the export location. IMO the feature should just use a folder as config parameter and then create a synced markdown export per note in zotero. Ideally filenames would be configurable, but I think something like the bibtex key would work since they are unique. Then I would the two-way sync still expect to work. So one can edit the notes from either obsidian or zotero. 
This would be amazing. 😍
@windingwind is this feasible? Or do you think there are issues of the current design of your plugin that would prevent this?
As far as I can tell, one would just need to fill `addon.data.sync.data` properly, right? Or would you expect performance problem then?

**Comment by ct2034** [comment]
Using bibtex keys as filename would also make it very compatible to https://github.com/mgmeyers/obsidian-zotero-integration, which would be nice.

**Comment by windingwind** [comment]
A quick answer:

1. you can always use a saved search to find all notes in your library. Then you can select all to export.
2. The filename can be customized with the Template feature.

**Comment by ct2034** [comment]
Ah ok. Thanks.
But I would have to do this again manually if I add a note.

**Comment by ct2034** [comment]
I am currently working with this
```
${Zotero.Items.get(noteItem.parentID).getField("citationKey")}.md
```
as template `Export MD File Name`. It produces some error messages. Presumably for all those notes that are not underneath something with a `citationKey`. And I don't know what it does if there are multiple notes per file. But it _kind of works_ for now. 🚀

If you are wondering, how to achieve the saved search, this is how:
![image](https://github.com/user-attachments/assets/d99601c8-9eac-4ab9-9eed-27521dc4e894)

**Comment by windingwind** [comment]
If there are multiple notes under an item, they just try to overwrite eachother's markdown and can be a mess. That's why the default template contains a key of the note item. You have to manually make sure all regular items only have one child note.

Also, for standalone notes that don't have a parent item, this template won't work.

Alsos, this is why I don't provide such an option to automatically export all notes in the library. People will definitely expect the plugin to export notes according to the collection's structure, but when you have multiple parent collections, you just don't know where to put the markdown file. You need to be very careful with the settings, otherwise it's just more than chaos.

I think you can use the _actions & tags_ plugin to write a script action and to set syncing for any new notes in your library. BN has APIs exposes in `Zotero.BetterNotes.apis` that allows you to control the syncing.
