### ISSUE TITLE
Embed linked notes in the note editor (not only when exporting)

### ISSUE THREAD

**Issue by psyguy** [windingwind/zotero-better-notes#131]
**Is your feature request related to a problem? Please describe.**

It is possible to make links to other notes in the main notes, but it is often helpful to actually embed the linked note in the main note.

**Describe the solution you'd like**

I don't know. Maybe implement it in a way similar to that of Obsidian, like `![linked-note]` instead of `[linked-note]` or something?
It would then be great if it gets (dynamically?) updated if the linked note changes.

**Describe alternatives you've considered**

I know it is possible when exporting the main note, though it would also be nice to have it in the note editor as well.

**Comment by windingwind** [comment]
Hi,

Embed the linked note to the main note here:

![image](https://user-images.githubusercontent.com/33902321/187919320-3587407c-38aa-4fe6-afd0-dc5b8ac84431.png)

**Comment by psyguy** [comment]
Wonderful! I didn't know that () How have I missed that? Thank you!

Is it also possible to have the embedded content updated (like the way it is updated almost instantly in the pop-up)? I could not figure out what the right arrows button does, but could they refresh the embedded note?

**Comment by windingwind** [comment]
Updating the embeded content is only possible if users DON’T modify the embeded note. Otherwise, we do not know how to update it.

The update also introduces a new problem, that the embede content can be in any format, even do not content anything is allowed, with the template function. That’s why we do not update the content.

Please consider using the popup or the preview pane in workspace window to preview linked note content.

**Comment by psyguy** [comment]
I see, thanks for the clarification, @windingwind!
