### ISSUE TITLE
[feature] Question on inserting citation of specific style into the note

### ISSUE THREAD

**Issue by E1phiph0ros** [windingwind/zotero-better-notes#161]
Hi! First of all, thank you from the bottom of my heart for creating this amazing plug-in - it literally saved me so many dreadful works to figuring out stuff on my own!!

My only question is the workflow of inserting citation - so what I have been doing so far is: first clikcing the ["] to generate a citation for a specific text, and then use [+] to insert it into the desired location in a note(please correct me if this is not how it supposed to work).
Per your instruction, I made sure to set up the Export- quick copy-item format as a citation format(in my case, I wish to use ASA(American Sociological Association 6th edition bibliography style). However, whenever I insert citation(through [+]) what appears is a shorter in-text citation(see red underlined in the screenshot) instead of the entire citation. 
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/108596710/193088835-5f2e9d23-ca7a-48d6-9fa8-e666eb79c03d.png">
How can i make it to something as showed up in your workflow example?
<img width="355" alt="image" src="https://user-images.githubusercontent.com/108596710/193090296-144811c7-cc9f-4819-a045-0ed342eeef9b.png">
Also I wonder if there is a good way to include citation in the note templates? As far as I search in your provided lists of templates, it seems that none of those support such feature right now. It'd be a great lot of help if you can give me some directions on how to figure out this on my own, if that's too much work.

Thank you so much for your time and help in advance!

**Comment by windingwind** [comment]
The `[+]` button is provided by Zotero. The citation text cannot be modified, that is why I do not recommend you to use this function if you want the citation in your own format.

The `"` button is provided by this plugin. The citation format can be set via menu->Edit->Note Citation Format(if the workspace tab/window is opened):

![image](https://user-images.githubusercontent.com/33902321/193295869-e2099fee-49bc-4d31-b581-95d8f78bcaf3.png)

The format setting here and the Zotero citation format in the preferences window do not affect each other.

To add the citation to the template would be a little bit complex. If you are familiar with JavaScript, the code is shown below:

```js
let format = Zotero.Knowledge4Zotero.template.getCitationStyle();
const cite = Zotero.QuickCopy.getContentFromItems(
  topItems, // Array<Zotero.Item>
  format,
  null,
  0
);
return cite.html;
```

Otherwise could you please describe the template function you want in detail so I can help you to build it?
