### ISSUE TITLE
[Bug] Invalid note for embedded-image attachment

### ISSUE THREAD

**Issue by dstillman** [windingwind/zotero-better-notes#212]
We're seeing some errors in the server logs from embedded-image attachments that somehow have what appear to be zotero-better-notes notes attached:

```
[
    {
        "key": "XM9ZAPZV",
        "version": 0,
        "itemType": "attachment",
        "parentItem": "6F93A25M",
        "linkMode": "embedded_image",
        "contentType": "image/png",
        "filename": "image.png",
        "mtime": 1667436642000,
        "md5": "[…]",
        "note": "<div data-schema-version=\"8\"><a href=\"zotero://note/u/PF4FQJZ3/\" rel=\"noopener noreferrer nofollow\">[text]</a>\n<p> </p>\n<a href=\"zotero://note/u/CR4J95CL/\" rel=\"noopener noreferrer nofollow\">[text]</a></div>",
        "dateAdded": "2022-11-03T00:50:41Z",
        "dateModified": "2022-11-03T01:10:29Z"
    }
]
```

This should never be possible, and it will cause sync breakage. We can block `note` from being assigned to embedded-image attachments, but that would just cause an error to be thrown, so this should be fixed in the plugin.

**Comment by windingwind** [comment]
I doubt if this is really caused by this plugin, as I've never tried to assign the `note` field to an image attachment.

As you can see in my code, no `_noteText` is directly accessed. I only use `item.setNote` in case the editor is not available and use the Prosemirror features or APIs if the editor is alive. The places where `setNote` is called are shown below:

1. In the setup wizard. It will create a user guide.
https://github.com/windingwind/zotero-better-notes/blob/eff2984e11d42cb5ead6e65f80381ce834e4b3cb/src/wizard/wizardWindow.ts#L274-L277

2. Create a new note (as the main note):
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/zotero/events.ts#L550-L553

3. Modify note content (without a note editor activated)
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteUtils.ts#L24-L42

This function is called in:
- Here the `targetNote` is from an editor instance.
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/editor/editorViews.ts#L732
- Here the `newNote` is from `await ZoteroPane_Local.newNote()`.
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteExportController.ts#L75
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteExportController.ts#L220
- Here the note content is read from `getLinesInNote`:
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteUtils.ts#L44
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteUtils.ts#L289
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteUtils.ts#L367
And this is `getLinesInNote`. It calls `item.getNote()`, which should not work successfully on an image attachment.
https://github.com/windingwind/zotero-better-notes/blob/40d761164ddcc796216bc16615fd76d804cad936/src/note/noteUtils.ts#L16-L22

I'm not sure if there are any other possible causes. As far as I can imagine, it's probably not caused by this plugin, but someone who uses this plugin happens to set the `note` field to an image attachment item.

**Comment by dstillman** [comment]
We've seen it from at least three different users in the last few days.

> someone who uses this plugin happens to set the note field to an image attachment item

But how would they do that? Embedded-image attachments appear solely as images in notes — they're not accessible any other way, other than via code. Hard to imagine that three different people have manually set these via code.

**Comment by windingwind** [comment]
If you have any idea about when this first appeared, maybe I could back to the last few releases of this plugin. However, there are no updates to the note write/create code for weeks(or even months).

Here are the commits: https://github.com/windingwind/zotero-better-notes/commits/master

Since Oct. 25, new commits are all about exporting notes to mindmap(.mm) and Docx, and a new image previewer.

One possibility I could think of is that someone published/shared a better note template(containing code that assigned a note to an image). That could explain why all these happen to users who use the this plugin.

**Comment by dstillman** [comment]
We're seeing it as far back as we have logs, which was August 20th.

**Comment by dstillman** [comment]
If you can't see a way you'd be causing, we can close this and we'll just put in a block, but whatever's triggering this might blow up when we do. Still, better than a permanent sync error later.

**Comment by windingwind** [comment]
I agree blocking it on the server side would solve this once and for all. We never know what users try to run.

I'd be glad to help anytime ^ ^

**Comment by dstillman** [comment]
It's already blocked on the server side. I mean we can block it on the client side, which might result in Zotero breaking. But it at least will happen at the time the relevant operation is done.

**Comment by windingwind** [comment]
Thank you very much. If there are reports about this blocked action, I'll try to figure out if it's related to this plugin.
