### ISSUE TITLE
LaTeX subscript showing as superscript

### ISSUE THREAD

**Issue by conchra** [windingwind/zotero-better-notes#37]
Current: Type a subscript only shows as superscript.
Image: as typed
<img width="463" alt="sshot-001" src="https://user-images.githubusercontent.com/16074663/171782639-9d076e90-c1d5-4c7b-934b-5b51d9f0ea90.png">

Image: after clicking LaTeX view button:
<img width="444" alt="sshot-002" src="https://user-images.githubusercontent.com/16074663/171782723-13eafe64-34de-4657-9d86-2b20330c1837.png">

It does not matter whether I use `$...$`, `$$...$$`, `\[...\], or \(...\)`.

**Comment by windingwind** [comment]
Hi, please try v0.4.12. The Katex is buggy due to firefox's strict origin rules and now we use MathJax to render LaTex in note.
Everything seems to be OK!

![image](https://user-images.githubusercontent.com/33902321/171803005-2af2ce64-6699-4165-b2b6-d476efdef719.png)


BTW, Only `$...$` and `$$...$$` are allowed now.

**Comment by conchra** [comment]
v0.4.12 works as expected now. Many thanks!
