### ISSUE TITLE
[Feature] to unify annotations and notes, after 15 years...

### ISSUE THREAD

**Issue by analytic-bias** [windingwind/zotero-better-notes#418]
**Is your feature request related to a problem? Please describe.**
Vid. https://forums.zotero.org/discussion/comment/12128/#Comment_12128
![image](https://user-images.githubusercontent.com/6694864/230765760-d26bb0a4-66a8-4a20-bfc1-375af87540f8.png)

**Describe the solution you'd like**
Loc. cit. I'd like to be able to put LaTeX equations and images into the annotation. The said "consolidation" would be nice.

**Comment by windingwind** [comment]
Hi,

BN provides a `Quick Note` which turns an annotation into a note. You can write the markdown or math in the annotation comment and they will be correctly converted in the generated note. Linking the note to your workspace so they can be exported in the embed/standalone mode later.

**Comment by cute-sayako** [comment]
@windingwind yes I know that. but is it possible for the add-on to synchronize between the annotation and notes or better to just embed the note into the annotation while still maintaining say the searchability from being a note?

also the quick note button always pops a new window or takes me to the workspace, instead of showing the note on the panel on the right...

**Comment by cute-sayako** [comment]
@windingwind Oh actually, is it possible to change the default behavior of clicking the quick note button from adding the note URL to the annotation to adding the line URL (with the query parameter `line`) to the annotation?

**Comment by windingwind** [comment]
Sorry for the delay. Keeping annotations in sync with notes is not that easy and necessary from my point of view. And embedding note into annotations? I'm not sure how this works.

As for the note link with line index, how should we decide which line to use?

**Comment by cute-sayako** [comment]
@windingwind For example one option will be to have a setting that when enabled, if the user has already put their cursor on a line in a note, then instead of creating a new note in a pop-up window, clicking the quick note button creates a bidirectional link between the annotation and the line. And maybe this can be further integrated with the list view and tree view etc, so that one can just use one note for each article or one main note to rule them all, instead of having to jump between scattered notes as it currently is.
