### ISSUE TITLE
[Feature] word account

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#83]
Hi! Me again! May I ask if this extension supports **"word account**"? I searched this key word and did not find any code in the template. I want to use "word account" function to track how many words this extension has helped me crazily note-down my learning from different literature. BTW, let me share one of my crazy note after using this extension to show my love for zotero better notes (hia hia)! THX in advance!
<img width="932" alt="image" src="https://user-images.githubusercontent.com/48398284/177412480-e5285650-4729-4edf-be5d-2908fb587e16.png">

_Originally posted by @KarenL01 in https://github.com/windingwind/zotero-better-notes/issues/23#issuecomment-1175477802_

**Comment by windingwind** [comment]
Hi, thanks for your like!
Maybe the word count is better to be a new feature rather than a template. Planned!

**Comment by windingwind** [comment]
![image](https://user-images.githubusercontent.com/33902321/177687848-2957a521-63db-435d-b069-c83d88137617.png)
v0.6.2可查看字数统计

**Comment by KarenL01** [comment]
Thank you, it worked! It amazed me again when I know how many words this extension has helped me note down in one main note. 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/48398284/177715726-f82c5555-1f7c-4487-b0c6-ba9097b6b254.png">

**Comment by KarenL01** [comment]
I checked the same note for the word account in Word and it only shows 7373 words rather than 41478 words in Zotero better notes. I wonder if zotero better notes counts every letter rather than a word so it shows a wrong word account number. I think that maybe it is because if you type in Chinese, and Chinese is one character=one word but in English, several letters/characters=one word, that might be one reason explaining the erros. Hope there is some solution(s) for this issue. 

Thank you for your reminder for sync but I don't use sync so it does not affect me that bad. :)

Thank you anyway for the quick uptates 💯
