### ISSUE TITLE
[Bug] The multi-level list do not fully display in the workspace

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-better-notes#87]
The multi-level list do not fully display in the workspace. Actually, I have more secondary headings in my notes! This bug didn't appear in **Release 0.6.2.**
![image](https://user-images.githubusercontent.com/88881853/178532164-ce6e6fbf-facf-4e9d-9f36-9ef485e30a89.png)

_Originally posted by @SSlovely in https://github.com/windingwind/zotero-better-notes/issues/84#issuecomment-1181931037_

**Comment by windingwind** [comment]
@SSlovely
Could you please provide a full screenshot of the workspace window/tab containing the disappeared headings, along with the left sidebar?

**Comment by SSlovely** [comment]
![image](https://user-images.githubusercontent.com/88881853/179351317-d7ff8e56-8f07-40ad-b200-8d170c4f9bfb.png)

Yeah, it just like this, I set these headings, but there are no corresponding displays here.

**Comment by windingwind** [comment]
I guess it's because you made a text color to the headings.
Could you please go to Edit->Note Template Editor and add a new template from this note, then copy-paste the template text here?

**Comment by SSlovely** [comment]
Thanks, and I found where is the bug! It's not about the color, but that's because the **monospaced** structure blocks the recognition of subsequent titles. While I delete this part, everything works fine.

![image](https://user-images.githubusercontent.com/88881853/179393210-e7e001b8-9c53-4448-b531-6cfb76887cab.png)

The html code for this part is: '''<pre>G/M=[<span style="color: black"><span style="background-color: white">t/(KC·ln2)</span></span>](1-2<sup>-C/t</sup>)</pre>'''. I would be very grateful to you if this problem could be fixed!

**Comment by windingwind** [comment]
Thanks. Will fix in the next release.

**Comment by SSlovely** [comment]
That's great! Thanks!
